#BSP:

        - description: 'wred-profile'
          type: object
          required:
            - uuid
            - profile-name
            - wred-profile-1-0:wred-profile-pac
          properties:
            uuid:
              type: string
            profile-name:
              type: string
              enum:
                - 'wred-profile-1-0:PROFILE_NAME_TYPE_WRED_PROFILE'
            wred-profile-1-0:wred-profile-pac:
              type: object
              required:
                - wred-profile-capability
                - wred-profile-configuration
              properties:
                wred-profile-capability:
                  $ref: '#/components/schemas/WRED_PROFILE_CAPABILITY'
                wred-profile-configuration:
                  $ref: '#/components/schemas/WRED_PROFILE_CONFIGURATION'


# wtp:

        - description: 'wred-template-profile'
          type: object
          required:
            - uuid
            - profile-name
            - wred-template-profile-1-0:wred-template-profile-pac
          properties:
            uuid:
              type: string
            profile-name:
              type: string
              enum:
                - 'wred-template-profile-1-0:PROFILE_NAME_TYPE_WRED_TEMPLATE_PROFILE'
            wred-template-profile-1-0:wred-template-profile-pac:
              type: object
              required:
                - wred-template-profile-capability
                - wred-template-profile-configuration
              properties:
                wred-profile-capability:
                  $ref: '#/components/schemas/WRED_TEMPLATE_PROFILE_CAPABILITY'
                wred-profile-configuration:
                  $ref: '#/components/schemas/WRED_TEMPLATE_PROFILE_CONFIGURATION'